name: All packages test

on: [pull_request]

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm ci
      - name: Test
        run: cd packages/css-in-js && npm run test
